<?php

/**
 * @file
 * Farm eggs.
 */

declare(strict_types=1);

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function farm_eggs_help(string $route_name, RouteMatchInterface $route_match): string {
  if ($route_name !== 'help.page.farm_eggs') {
    return '';
  }
  $text = file_get_contents(__DIR__ . '/README.md');
  if ($text === FALSE) {
    return '';
  }
  if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
    return '<pre>' . Html::escape($text) . '</pre>';
  }
  // Use the Markdown filter to render the README.
  $filter_manager = \Drupal::service('plugin.manager.filter');
  $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
  $config = ['settings' => $settings];
  /** @var \Drupal\filter\Plugin\FilterInterface */
  $filter = $filter_manager->createInstance('markdown', $config);
  return $filter->process($text, 'en');
}

/**
 * Implements hook_farm_entity_bundle_field_info().
 *
 * Adds 'Produces eggs' field to group and animal assets.
 */
function farm_eggs_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle): array {
  $fields = [];
  if ($entity_type->id() == 'asset' && in_array($bundle, ['group', 'animal'])) {
    $options = [
      'type' => 'boolean',
      'label' => t('Produces eggs'),
      'description' => t('Checking this box will make this asset available in the <a href="@egg_form_path">egg harvest form</a>.', ['@egg_form_path' => '/quick/eggs']),
      'weight' => [
        'form' => 30,
        'view' => -30,
      ],
      'view_display_options' => [
        'label' => 'inline',
        'type' => 'asset_produces_eggs',
        'settings' => [
          'record_egg_harvest_button' => TRUE,
        ],
      ],
    ];
    $fields['produces_eggs'] = \Drupal::service('farm_field.factory')->bundleFieldDefinition($options);
  }
  return $fields;
}

/**
 * Implements hook_gin_content_form_routes().
 *
 * Improve egg harvest form layout.
 */
function farm_eggs_gin_content_form_routes(): array {
  return [
    'farm.quick.eggs',
  ];
}

/**
 * Implements hook_theme();
 */
function farm_eggs_theme() {
  return [
    'node_edit_form' => [
      'render element' => 'form',
    ],
  ];
}
